config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/dashboard', to: 'users#show'
  get '/resources', to: 'resources#show'
  post '/entry/calculate', to: 'entries#get_api_nutrients'

  get 'auth/facebook/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :date
  validates_presence_of :meal
  validates_presence_of :ingredients
end

app/models/macronutrients.rb
class Macronutrients
  def self.collect_macronutrients(parsed_data)
    parsed_data.map do |ingredient|
      { ingredient[:ingredients][0][:text] => {
        fat: ingredient[:totalNutrients][:FAT] ? ingredient[:totalNutrients][:FAT][:quantity] : 0,
        carbs: ingredient[:totalNutrients][:CHOCDF] ? ingredient[:totalNutrients][:CHOCDF][:quantity] : 0,
        protein: ingredient[:totalNutrients][:PROCNT] ? ingredient[:totalNutrients][:PROCNT][:quantity] : 0
        }
      }
    end
  end

  def self.sum_macronutrients(nutrients)
    values = nutrients.map { |hash| hash.values }.flatten
    summed = {}
    summed[:fat] = values.inject(0) { |sum, hash| sum + hash[:fat].floor }
    summed[:carbs] = values.inject(0) { |sum, hash| sum + hash[:carbs].floor }
    summed[:protein] = values.inject(0) { |sum, hash| sum + hash[:protein].floor }
    summed
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :entries

  def self.find_or_create_by_auth(auth)
    user = User.find_or_create_by(provider: auth["provider"], uid: auth["uid"])

    user.name = auth["info"]["name"]
    user.email = auth["info"]["email"]
    user.image_url = auth["info"]["image"]
    user.oauth_token = auth["credentials"]["token"]
    user.oauth_expires_at = auth["credentials"]["expires_at"]

    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user,
                :unauthenticated_user_error

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def unauthenticated_user_error
    render(file: "/public/404") unless current_user
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :check_user, only: [:show, :edit]

  def new
    if current_user
      @entry = Entry.new(date: Date.today)
      @entry.meal = params["meal"] if params["meal"]
      @entry.date = params["date"] if params["date"]
    else
      unauthenticated_user_error
    end
  end

  def create
    @entry = Entry.create(entry_params)
    @entry.user_id = current_user.id
    if @entry.save
      meal_data = { ingredients: params["entry"]["ingredients"].split(/ *, */) }
      calc_nutrients(meal_data)
      redirect_to dashboard_path
      flash[:success] = "New meal logged!"
    else
      flash[:error] = @entry.errors.full_messages.join(", ")
      redirect_to new_entry_path
    end
  end

  def show
    check_user
  end

  def edit
    check_user
  end

  def update
    if current_user
      @entry = Entry.find(params[:id])
      @entry.update_attributes(entry_params)
      get_updated_nutrients(params)
      flash[:success] = "Meal updated"
      redirect_to entry_path(@entry)
    else
      unauthenticated_user_error
    end
  end

  def destroy
    if current_user
      @entry = Entry.find(params[:id])
      @entry.destroy
      flash[:warning] = "Meal deleted"
      redirect_to dashboard_path
    else
      unauthenticated_user_error
    end
  end

  def get_api_nutrients
    if params[:ingredients]
      meal_data = { ingredients: params[:ingredients].split(/ *, */) }
      ns = NutritionService.new
      nutrients = ns.get_nutrition_values(meal_data)
      if nutrients[:result] == "error"
        render :json => { :result => "error", :message => nutrients[:message] }
      else
        summed_nutrients = Macronutrients.sum_macronutrients(nutrients[:response])
        render :json => { :result => "success", :nutrients => summed_nutrients }
      end
    end
  end

  def get_updated_nutrients(params)
    meal_data = { ingredients: params["entry"]["ingredients"].split(/ *, */) }
    calc_nutrients(meal_data)
  end

  private

  def entry_params
    params.require(:entry).permit(:date,
                                  :meal,
                                  :ingredients,
                                  :fat,
                                  :carbs,
                                  :protein,
                                  :notes,
                                  :user_id)
  end

  def calc_nutrients(meal_data)
    ns = NutritionService.new
    nutrients = ns.get_nutrition_values(meal_data)
    summed_nutrients = Macronutrients.sum_macronutrients(nutrients[:response])
    @entry.update_attributes(summed_nutrients)
    @entry.save
  end

  def check_user
    if current_user
      @entry = Entry.find(params[:id])
    else
      unauthenticated_user_error
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by_auth(request.env["omniauth.auth"])
    if @user
      session[:user_id] = @user.id
      redirect_to dashboard_path
      flash[:success] = "Welcome #{@user.name}!"
    else
      redirect_to root_path
      flash[:warning] = "Try again!"
    end
  end

  def destroy
    if current_user
      session.destroy
      flash[:success] = "You have successfully logged out"
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @presenter = DashboardPresenter.new(current_user)
    else
      unauthenticated_user_error
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/edit.html.erb
<%= render partial: "partials/navbar" %>
<body class="container new-entry">
  <p class="edit-header">Edit your meal:</p>
  <div class="container entry-form">
    <%= form_for @entry do |f| %>
    <div class="row">
      <div class="form-group col-sm-6">
        <%= f.label :date %>:
        <%= f.date_field :date, value: @entry.date.strftime("%Y-%m-%d"), class:"form-control dropdown-text" %>
      </div>
      <div class="form-group col-sm-6">
        <%= f.label :meal %>:
        <%= f.select :meal, options_for_select(["Breakfast", "Lunch", "Dinner", "Snack"], @entry.meal), {}, { class:"form-control dropdown-text" } %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :ingredients %>:
      <%= f.text_area :ingredients, class:"form-control form-text", rows:"5" %>
    </div>
    <div class="form-group">
      <%= f.label :notes %>:
      <%= f.text_area :notes, class:"form-control form-text", rows:"7" %>
    </div>
      <%= f.hidden_field :fat %>
      <%= f.hidden_field :carbs %>
      <%= f.hidden_field :protein %>

      <%= f.submit "UPDATE MEAL", class: "btn btn-info submit-btn", id: "form-submit" %>
      <%= link_to "CALCULATE", "#", class: "btn btn-info submit-btn", id: "calc-values" %>
      <p class="form-control-static pull-right">
        Fat: <span class="fat-val"><%= @entry.fat ? @entry.fat : 0 %></span>g
        | Carbs: <span class="carb-val"><%= @entry.carbs ? @entry.carbs : 0%></span>g
        | Protein: <span class="protein-val"><%= @entry.protein ? @entry.protein : 0%></span>g
      </p>
    <% end %>
  </div>
</body>

app/views/entries/index.html.erb
<%= render partial: "partials/navbar" %>

<body class="user-dashboard">
  <div class="container">
    <div class="text-center"><%= link_to "Create New Entry", new_user_entry_path, class: "btn btn-default entry-btn" %></div>
    <table class="table table-bordered table-responsive table-hover entries-table">
    <thead>
      <tr>
        <th class="text-center" width="15%">DATE</th>
        <th class="text-center" width="17%">BREAKFAST</th>
        <th class="text-center" width="17%">LUNCH</th>
        <th class="text-center" width="17%">DINNER</th>
        <th class="text-center" width="17%">SNACKS</th>
        <th class="text-center" width="17%">TOTALS</th>
      </tr>
    </thead>
    <tbody>
      <% if current_user.entries.count == 0 %>
        <tr>
          <td class="text-center date-column"></td>
          <td class="text-center breakfast-column"><%= link_to "+", @entry, class: "btn btn-lg btn-success" %></td>
          <td class="text-center lunch-column"><%= link_to "+", @entry, class: "btn btn-lg btn-success" %></td>
          <td class="text-center dinner-column"><%= link_to "+", @entry, class: "btn btn-lg btn-success" %></td>
          <td class="text-center snack-column"><%= link_to "+", @entry, class: "btn btn-lg btn-success" %></td>
          <td class="text-center totals-column"></td>
        </tr>
      <% else %>
        <% @entries.values.each do |day_entries| %>
        <tr>
          <td><%= day_entries[0].date.strftime("%a %b %e, %Y") %></td>
          <td>
            <% if breakfast(day_entries[0]) %>
              Fat: <%= breakfast(day_entries[0])[0].fat %><br>
              Carbs: <%= breakfast(day_entries[0])[0].carbs %><br>
              Protein: <%= breakfast(day_entries[0])[0].protein %><br>
            <% else %>
              <%= link_to "+", new_user_entry_path(date: sort_by_meal(day_entries)[0].date, meal: "breakfast"), class: "btn btn-lg btn-success add-entry-btn" %>
            <% end %>
          </td>
          <% if lunch(day_entries[2]) %>
            Fat: <%= lunch(day_entries[2])[0].fat %><br>
            Carbs: <%= lunch(day_entries[2])[0].carbs %><br>
            Protein: <%= lunch(day_entries[2])[0].protein %><br>
          <% else %>
            <%= link_to "+", new_user_entry_path(date: sort_by_meal(day_entries)[2].date, meal: "lunch"), class: "btn btn-lg btn-success add-entry-btn" %>
          <% end %>
          <td>
          </td>
          <td>d</td>
          <td>s</td>
          <td>t</td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  </div>
</body>

app/views/entries/new.html.erb
<%= render partial: "partials/navbar" %>

<body class="new-entry">
  <div id="form-errors" class="flashes" style="display:none;"></div>
  <div class="container entry-form">
    <%= form_for @entry do |f| %>
    <div class="row">
      <div class="form-group col-sm-6">
        <%= f.label :date %>:
        <%= f.date_field :date, value: @entry.date.strftime("%Y-%m-%d"), class:"form-control dropdown-text" %>
      </div>
      <div class="form-group col-sm-6">
        <%= f.label :meal %>:
        <%= f.select :meal, options_for_select(["Breakfast", "Lunch", "Dinner", "Snack"], @entry.meal), {}, { class:"form-control dropdown-text" } %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :ingredients %>:
      <div id="ingr-instructions">
        Enter each of your ingredients separated by a comma. Include the amount and quantity
        or size for each item like so:<br><strong><u>"1 small apple, 3oz bacon, 1 cup kale, 12g almonds".</strong></u> (Yes, either metric or imperial values are fine!)
      </div>
      <%= f.text_area :ingredients, placeholder:"nom nom nom", class:"form-control form-text", rows:"5" %>
    </div>
    <div class="form-group">
      <%= f.label :notes %>:
      <%= f.text_area :notes, placeholder:"how are you feeling today?", class:"form-control form-text", rows:"7" %>
    </div>
      <%= f.hidden_field :fat %>
      <%= f.hidden_field :carbs %>
      <%= f.hidden_field :protein %>

      <%= f.submit "SAVE", class: "btn btn-info submit-btn", id: "form-submit" %>
      <%= link_to "CALCULATE", "#", class: "btn btn-info submit-btn", id: "calc-values" %>
      <p class="form-control-static pull-right">
        Fat: <span class="fat-val"><%= @entry.fat ? @entry.fat : 0 %></span>g
        | Carbs: <span class="carb-val"><%= @entry.carbs ? @entry.carbs : 0%></span>g
        | Protein: <span class="protein-val"><%= @entry.protein ? @entry.protein : 0%></span>g
      </p>
    <% end %>
  </div>
</body>

app/views/entries/show.html.erb
<%= render partial: "/partials/navbar" %>
<body class="meal-show">
  <div class="container">
    <div class="meal_data">
      <p class="meal-title"><%= @entry.meal %> for <%= @entry.date.strftime("%a %b %e, %Y") %></p>
      <p class="meal-ingr">Ingredients: <%= @entry.ingredients %></p><br>
      <p class="meal-data">Total Macronutrient Intake: </p>
      <div class="meal-nutrients">
        <div class="nutrient-block">
          <p>Fat: <%= @entry.fat %>g</p>
          <p>Carbs: <%= @entry.carbs %>g</p>
          <p>Protein: <%= @entry.protein %>g</p>
        </div>
      </div><br><br>
      <p class="notes">Notes: </p>
      <div class="notes-block">
        <div class="meal-notes">
          <%= @entry.notes %>
        </div>
      </div>
      <br><br>
      <%= link_to "Edit Entry", edit_entry_path(@entry), class: "btn btn-info edit-btn" %>
      <%= link_to "Delete Entry", @entry, method: :delete, class: "btn btn-info delete-btn" %>
    </div>
  </div>
</body>

app/views/home/index.html.erb
<div>
  <div class="grayscale">
    <%= image_tag "veggies.jpg", class: "veggie-pic" %>
    <p class="title-main">PaleoPal</p>
    <%= render partial: "partials/user_buttons", id: "upper-landing-login-btn" %>
    <%= render partial: "partials/tagline" %>
  </div><!-- End of upper section with image -->

  <div class="testimonials">
    <%= render partial: "partials/user_testimonials" %>
  </div><!-- End of testimonial section -->

  <div class="how-it-works grayscale">
    <div class="container">
      <p class="how-header">How Does it Work?</p>
      <div class="row">
        <div class="col-sm-6">
          <%= render partial: "partials/how_it_works" %>
        </div>
        <div class="col-sm-6">
          <%= render partial: "partials/screenshots" %>
        </div>
      </div>
    </div>
  </div><!-- End of how-it-works section -->
  <p class="resources-link">Check out all of our helpful Paleo resources <%= link_to "here", resources_path %></p><br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Dawning+of+a+New+Day|Amatic+SC|Reenie+Beanie|Quicksand' rel='stylesheet' type='text/css'>
  <title>PaleoPal</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>

<% flash.each do |type, msg| %>
  <div class="flashes">
    <%= content_tag :div, msg %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/partials/_how_it_works.html.erb
<p class="how-text rounded">
  1. Easily sign in with your Facebook account <br><br>
  2. Click "Create First Entry" from your dashboard <br><br>
  3. Enter the date, the meal, the ingredients, and <br>
     any other details you would like to remember <br><br>
  4. Click "Calculate" to see your macronutrient <br>
     intake for that meal or "Save" to save the <br>
     entry to your journal <br><br>
  5. Visit your dashboard at any time to see a <br>
     running list of all your saved days and meals <br><br>
  6. Visit "Resources" to see guidelines, recipes <br>
     shopping tips and more!!
</p>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <% if current_user %>
      <%= link_to image_tag(current_user.image_url), root_path, class: "user-image-nav rounded" %>
      <%= link_to "Resources", resources_path, class: "btn btn-default navbar-btn" %>
      <%= link_to "Profile", "#", class: "btn btn-default navbar-btn" %>
      <%= link_to "Dashboard", dashboard_path, class: "btn btn-default navbar-btn" %>
      <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-default navbar-btn" %>
    <% end %>
</nav>

app/views/partials/_screenshots.html.erb
<div class="screenshots">
  <div class="screenshot">
    <%= image_tag "paleopal-dashboard.jpg", class: "screenshot-img", width: "700" %>
  </div>
  <div class="screenshot">
    <%= image_tag "paleopal-add-new.jpg", class: "screenshot-img", width: "700" %>
  </div>
</div>

app/views/partials/_tagline.html.erb
<div class="tagline rounded">
  Welcome! <br>
  PaleoPal is your new BFF, here to help with all your <br>
  food diary needs as you transition to a healthier and <br>
  more vibrant YOU! Log your meals, write about your symptoms, <br>
  see your nutrient intake for every meal and every day... <br>
  Let the healing journey begin!
</div>

app/views/partials/_user_buttons.html.erb
<div class="user-buttons">
  <% if current_user %>
    <%= link_to "Go to my Dashboard!", dashboard_path, class: "btn btn-lg btn-default btn-home dashboard-btn" %>
  <% else %>
    <%= link_to "Login with Facebook", "/auth/facebook", class: "btn btn-lg btn-default btn-home login-btn" %>
  <% end %>
</div>

app/views/partials/_user_dashboard.html.erb
<% if current_user.entries.count > 0 %>
  <table class="table table-bordered table-responsive table-hover entries-table">
    <thead>
      <tr>
        <th class="text-center" width="15%">DATE</th>
        <th class="text-center" width="17%">BREAKFAST</th>
        <th class="text-center" width="17%">LUNCH</th>
        <th class="text-center" width="17%">DINNER</th>
        <th class="text-center" width="17%">SNACKS</th>
        <th class="text-center" width="17%">TOTALS</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @presenter.get_day_entries.each do |day_entry| %>
      <td class="text-center date-column"><%= day_entry.date.strftime("%a %b %e, %Y") %></td>
        <% @presenter.meals.each do |meal| %>
        <% if current_user.entries.where(date: day_entry.date).exists?(meal: meal) %>
          <td class="text-center meal-column">Fat: <%= @presenter.meal_data(day_entry, meal)[:fat] %>g<br>
                                                   Carbs: <%= @presenter.meal_data(day_entry, meal)[:carbs] %>g<br>
                                                   Protein: <%= @presenter.meal_data(day_entry, meal)[:protein] %>g<br>
          <%= link_to "View Entry", entry_path(@presenter.get_meal_entry_id(day_entry.date, meal)), class: "btn btn-default view-btn" %></td>
        <% else %>
          <td class="text-center meal-column"><%= link_to "+", new_entry_path(date: day_entry.date, meal: meal), class: "btn btn-lg btn-success add-entry-btn" %></td>
        <% end %>
      <% end %>
      <td class="text-center totals-column">Fat: <%= @presenter.get_day_totals(day_entry)[:fat] %>g<br>
        Carbs: <%= @presenter.get_day_totals(day_entry)[:carbs] %>g<br>
        Protein: <%= @presenter.get_day_totals(day_entry)[:protein] %>g</td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="jumbotron" style="margin-top: 60px;">
    <p align="center">Welcome to PaleoPal!</p>
    <p align="center">Congratulations on starting on the path to real food awareness and health... Let the healing journey begin!</p>
    <p align="center"><strong>You don't have any meals entered. Click "Create a New Entry" above to get started</strong></p>
  </div>
<% end %>

app/views/partials/_user_testimonials.html.erb
<div class="testimonials">
  <div class="testimonial-header">
    <h2>OUR USERS LOVE US...</h2>
  </div>
  <div class="row">
    <div class="testimonial col-md-4">
      <p>"I thought I was eating so much <br>
        differently than I actually was! <br>
        PaleoPal allowed me to see where <br>
        my nutritional deficits were so I <br>
        could get on the path to true health."</p>
    </div>
    <div class="testimonial col-md-4">
      <p>"I lost 20 pounds and feel amazing <br>
          on the Paleo diet! I had tried several <br>
          times to start the diet on my own and <br>
          failed. Using PaleoPal really kept me <br>
          on track."</p>
    </div>
    <div class="testimonial col-md-4">
      <p>"This app is amazing. It really helped <br>
        me get organized and stay motivated. <br>
        I have definitley built habits I know <br>
        will be with me the rest of my life!"</p>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
<%= render partial: "partials/navbar" %>
<div class="container resources">
  <div class="row">
    <div class="col-sm-3">
      <%= image_tag "allium.jpg", class: "veggie-pic" %>
    </div>
    <div class="col-sm-8 col-sm-offset-1">
      The basic tenants of a Paleo diet are that you want your macronutrient intake to
      be primarily from fat with moderate protein and low carbohydrates. These nutrients
      should come from high quality whole foods.<br>
      The basics are as such: <br>
      <strong><u>YES:</strong></u><br>
      <strong>Fruit</strong> - though try to avoid really sugary fruits like mango, pineapple, bananas, etc.
      and stick with things like berries, apples, plantains, etc.<br>
      <strong>Vegetables</strong> - pretty much all of them, though try to avoid/limit white potatoes and
      other really starchy things (go for sweet potatoes instead). Also no corn,
      as it's a grain. You want tons of leafy greens, onions and garlic, and veggies
      that encompass the full spectrum of colors.<br>
      <strong>Oils</strong> - stick with just olive, coconut, avocado, and animal
      fats/lard (from a good source).<br>
      <strong>Coconut</strong> - every form of it! Coconut will be your best friend,
      especially when you find yourself missing dairy. Coconut oil, butter, milk, cream,
      flakes - you name it. Cook with the oil, put the cream in your coffee, replace
      butter in baked recipes with the oil or butter or cream.<br>
      <strong>Meat</strong> - Wild fish and pastured/grass-fed/wild meats are what you want,
      a good portion at each meal ideally. 60-70 grams of protein per day would be optimal.<br>
      <strong>Eggs</strong> - pasteured, organic<br>
      <strong>Nuts & Seeds</strong> - ideally soaked and dehydrated<br>
      <strong>Fermented foods</strong> - sauerkraut, kimchi, etc.<br><br>
      <strong><u>NO:</strong></u><br>
      <strong>Dairy</strong><br>
      <strong>Grains</strong><br>
      <strong>Legumes (beans)</strong><br>
      <strong>White potatoes</strong><br>
      <strong>Processed foods</strong><br>
      <strong>Vegetable oils (corn, soy, canola, etc.)</strong><br>
      <strong>Sugar (small amounts of honey and maple are fine)</strong><br>
      <strong>Alcohol</strong><br><br>
      <a href="http://www.marksdailyapple.com/definitive-guide-to-the-primal-eating-plan/">The Definitive Guide to the Primal Eating Plan</a><br>
      <a href="http://paleoiq.com/macronutrient-ratios/">Mother Nature's Perfect Macronutrient Ratio</a><br>
      <a href="http://paleoleap.com/paleo-diet-faq/">Paleo FAQ</a><br>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "partials/navbar" %>
<body class="user-dashboard">
  <div class="container">
    <div class="text-center">
      <%= link_to "Create New Entry", new_entry_path, class: "btn btn-success entry-btn" %>
    </div>
      <%= render partial: "partials/user_dashboard" %>
  </div>
</body>